import type { Language, TonePreset } from '../types';

export const TONE_PRESETS: TonePreset[] = [
  {
    id: 'original',
    name: 'Natural Studio',
    tag: 'Pure & Crisp',
    description: 'Clean high-fidelity vocal with light studio mastering and warm limiter.',
    primaryColor: '#00f2fe',
    secondaryColor: '#4facfe',
    glowColor: 'rgba(0, 242, 254, 0.4)',
    iconName: 'Mic',
    pitchShift: 0,
    reverbAmount: 0.05,
    distortionAmount: 0,
    ringModFreq: 0,
  },
  {
    id: 'demon',
    name: 'Titan Demon',
    tag: 'Deep Sub-Bass',
    description: 'Downshifted demonic roar with cavernous reverb and heavy sub-harmonics.',
    primaryColor: '#ff0844',
    secondaryColor: '#ff4e50',
    glowColor: 'rgba(255, 8, 68, 0.5)',
    iconName: 'Flame',
    pitchShift: -7,
    reverbAmount: 0.65,
    distortionAmount: 0.35,
    ringModFreq: 0,
  },
  {
    id: 'robot',
    name: 'Cyber Dalek',
    tag: 'Ring Modulated',
    description: 'Robotic metallic timbre created via 65Hz ring modulation and bit-clipping.',
    primaryColor: '#00ff87',
    secondaryColor: '#60efff',
    glowColor: 'rgba(0, 255, 135, 0.5)',
    iconName: 'Bot',
    pitchShift: 0,
    reverbAmount: 0.1,
    distortionAmount: 0.45,
    ringModFreq: 65,
  },
  {
    id: 'chipmunk',
    name: 'Pixie Chipmunk',
    tag: 'High Pitch',
    description: 'Up-shifted +8 semitones with sparkly highs and hyper-energetic resonance.',
    primaryColor: '#ff758c',
    secondaryColor: '#ff7eb3',
    glowColor: 'rgba(255, 117, 140, 0.5)',
    iconName: 'Sparkles',
    pitchShift: 8,
    reverbAmount: 0.15,
    distortionAmount: 0,
    ringModFreq: 0,
  },
  {
    id: 'walkietalkie',
    name: 'Walkie-Talkie',
    tag: 'Lo-Fi Radio',
    description: 'Narrow 400Hz-3.2kHz telecom bandpass with grit, radio squelch & overdrive.',
    primaryColor: '#f7971e',
    secondaryColor: '#ffd200',
    glowColor: 'rgba(247, 151, 30, 0.5)',
    iconName: 'Radio',
    pitchShift: 0,
    reverbAmount: 0.05,
    distortionAmount: 0.7,
    ringModFreq: 0,
    bandpassRange: [450, 3200],
  },
  {
    id: 'ethereal',
    name: 'Astral Spirit',
    tag: 'Cosmic Shimmer',
    description: 'Dreamy cathedral reverb with 450ms stereo ping-pong delay and spatial halo.',
    primaryColor: '#b19fff',
    secondaryColor: '#e0c3fc',
    glowColor: 'rgba(177, 159, 255, 0.5)',
    iconName: 'Ghost',
    pitchShift: 1,
    reverbAmount: 0.85,
    distortionAmount: 0,
    ringModFreq: 0,
  },
  {
    id: 'alien',
    name: 'Cosmic Alien',
    tag: 'Frequency Warp',
    description: 'Double FM vibrato with resonant alien sweep and deep space oscillation.',
    primaryColor: '#7f00ff',
    secondaryColor: '#e100ff',
    glowColor: 'rgba(225, 0, 255, 0.5)',
    iconName: 'Zap',
    pitchShift: -2,
    reverbAmount: 0.4,
    distortionAmount: 0.25,
    ringModFreq: 110,
  },
];

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', flag: '🇺🇸', nativeName: 'English', ttsLang: 'en-US' },
  { code: 'es', name: 'Spanish', flag: '🇪🇸', nativeName: 'Español', ttsLang: 'es-ES' },
  { code: 'fr', name: 'French', flag: '🇫🇷', nativeName: 'Français', ttsLang: 'fr-FR' },
  { code: 'de', name: 'German', flag: '🇩🇪', nativeName: 'Deutsch', ttsLang: 'de-DE' },
  { code: 'hi', name: 'Hindi', flag: '🇮🇳', nativeName: 'हिन्दी', ttsLang: 'hi-IN' },
  { code: 'bn', name: 'Bengali', flag: '🇧🇩', nativeName: 'বাংলা', ttsLang: 'bn-IN' },
  { code: 'ja', name: 'Japanese', flag: '🇯🇵', nativeName: '日本語', ttsLang: 'ja-JP' },
  { code: 'ko', name: 'Korean', flag: '🇰🇷', nativeName: '한국어', ttsLang: 'ko-KR' },
  { code: 'zh', name: 'Chinese', flag: '🇨🇳', nativeName: '中文 (普通话)', ttsLang: 'zh-CN' },
  { code: 'it', name: 'Italian', flag: '🇮🇹', nativeName: 'Italiano', ttsLang: 'it-IT' },
  { code: 'pt', name: 'Portuguese', flag: '🇧🇷', nativeName: 'Português', ttsLang: 'pt-BR' },
  { code: 'ar', name: 'Arabic', flag: '🇸🇦', nativeName: 'العربية', ttsLang: 'ar-SA' },
  { code: 'ru', name: 'Russian', flag: '🇷🇺', nativeName: 'Русский', ttsLang: 'ru-RU' },
];
